export const UPDATE_DISPLAY_MODE = "UPDATE_DISPLAY_MODE";
export const UPDATE_SELECTED_USER = "UPDATE_SELECTED_USER";
export const FETCH_USER_REPOS = "FETCH_USER_REPOS";
export const ON_USER_REPOS_FETCH = "ON_USER_REPOS_FETCH";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const ON_USER_DETAILS_FETCH = "ON_USER_DETAILS_FETCH";
